<?php

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function export_users_help($path, $arg) {
	$output = '';
	switch ($path) {
		case "admin/help#export_users" :
			$output = '<p style=color:red>' . t("Exports all users details is csv file.") . '</p>';
			break;			
	}
	return $output;
} 

/**
 * Implementation of hook_perm().
 */
function export_users_perm() {
	return array (
		'access export_users content'		
	);
} 

/**
 * Implementation of hook_menu().
 */

function export_users_menu() {	
	$items['user/export'] = array (
		'title' => t('Export Users Details in CSV'),
		'description' => t('Export Users'),
		'page callback' => 'export_users_csv',		
		'access arguments' => array('access export_users content'),		
		'type' => MENU_NORMAL_ITEM,
		'weight' => -8,
	);	
	return $items;
}

/**
* Implementation of custom hook_csv, which returns the users details in csv format and prompt the User to Save the file.
*/

function export_users_csv() {
	
	$_csv_data = 'User Id, User Name, User Email, User Status, User Created Date, User Last Access Date'. "\n";
	drupal_set_header("Content-type: application/octet-stream");
	drupal_set_header("Content-Disposition: attachment; filename=\"users-data.csv\"");
	$result = db_query('SELECT DISTINCT u.uid, u.name, u.mail as email, u.status, u.created, u.access FROM {users} u LEFT JOIN {users_roles} ur ON u.uid = ur.uid WHERE u.uid > 0');
	while ($account = db_fetch_object($result))
	{
		$created = date("m.d.y", $account->created);
		$access =  date("m.d.y", $account->access);
		$_csv_data .= $account->uid.','.$account->name.','.$account->email.','.$account->status.','.$created.','.$access . "\n";
	}
	echo $_csv_data;
}